version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: linux
    group: linux

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: linux
