name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.DBAPPLICATION }}" > ./src/main/resources/application-db.properties
      - run: cat ./src/main/resources/application.properties
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.OAUTHAPPLICATION }}" > ./src/main/resources/application-oauth.properties
      - run: cat ./src/main/resources/application.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      ## build Docker and Push Docker Hub
      - name: build with Gradle
        run: ./gradlew clean build
      - name: build Docker
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -t spring-cicd .
          docker tag spring-cicd:latest bemobemo/spring-cicd:latest
          docker push bemobemo/spring-cicd:latest
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          port: 22
          script: who am i
